export const DATA = {
  name: "Riku Rainio",
  role: "Software Developer",
  about: "Building stuff with code",
  links: {
    Email: "mailto:rainioriku@gmail.com",
    GitHub: "https://github.com/rikurainio",
    Instagram: "https://www.instagram.com/rikurainio/",
    LinkedIn: "https://linkedin.com/in/rikurainio",
    Resume: "/cv.pdf", // Place in public folder
  },
  skills: [
    { name: "TypeScript", category: "programming language" },
    { name: "JavaScript", category: "programming language" },
    { name: "C++", category: "programming language" },
    { name: "Python", category: "programming language" },
    { name: "Next.js", category: "framework" },
    { name: "React", category: "framework" },
    { name: "HTML", category: "markup" },
    { name: "CSS", category: "styling" },
    { name: "TailwindCSS", category: "styling framework" },
    // { name: "Electron", category: "framework" },
    { name: "Node.js", category: "runtime" },
    { name: "AWS", category: "cloud" },
    { name: "PostgreSQL", category: "database" },
    { name: "MongoDB", category: "database" },
    { name: "Redis", category: "database" },
    { name: "Git", category: "tool" },
    { name: "Cursor", category: "tool" },
    { name: "Photoshop", category: "design tool" },
    { name: "Sony Vegas Pro", category: "design tool" },
    { name: "Figma", category: "design tool" },
    { name: "Godot", category: "engine" },
    { name: "Lugia", category: "pokemon" },
  ],
  projects: [
    {
      title: "Drafter.lol",
      slug: "drafter-lol",
      description: "A real-time drafting and analytics platform for League of Legends teams, coaches, and broadcasters",
      tech: ["Next.js", "Socket.io", "Polar", "TypeScript", "PostgreSQL"],
      link: "https://drafter.lol",
      image: "drafter.jpg",
      accentColor: "emerald",
    },
    {
      title: "Warehouse Jiu Jitsu app",
      slug: "warehousejiujitsu",
      description: "A mobile application for warehouse jiu-jitsu betting with fake credits",
      tech: ["Next.js", "Socket.io", "Oauth", "TypeScript"],
      link: "https://definitelynotgambling.online",
      image: "warehousejj2.png",
      accentColor: "violet",
    },
    {
      title: "Mennää Game",
      slug: "mennaa",
      description: "A Godot game project",
      tech: ["Godot", "GDScript"],
      link: "",
      image: "mennaa.png",
      accentColor: "sky",
    },

    {
      title: "Sasken CV Database",
      slug: "sasken-cv-database",
      description: "A CV database application for Sasken",
      tech: ["React", "Django", "PostgreSQL"],
      link: "",
      image: "sasken.png",
      accentColor: "amber",
    },

    {
      title: "LinkedInsanity job applier",
      slug: "linkedinsanity",
      description: "Automated LinkedIn Easy Applier with customazible settings",
      tech: ["JavaScript", "Browser Automation"],
      link: "",
      image: "linkedinsanity.png",
      accentColor: "rose",
    },
  ],
  jobs: [
    {
      company: "DataAnnotation",
      role: "AI Annotator",
      period: "March 2024 – February 2026",
      description: "Improved text-based language models by rating prompts based on correctness, cohesiveness, verbosity, and context, including testing models with complex, carefully crafted prompts. Analyzed and corrected code to optimize performance, fix bugs, and enhance overall code quality in various projects.",
    },
    {
      company: "Buutti",
      role: "Software Developer",
      period: "April 2024 – October 2024",
      description: "Developed a full-stack webshop, working closely with the client to design and implement custom features that met their needs. Integrated APIs, optimized backend processes, and improved the frontend for a better user experience.",
    },
    {
      company: "Knowit",
      role: "Software Developer",
      period: "August 2022 – March 2024",
      description: "Led frontend development using React, integrating seamlessly with AWS backend services to deliver a quality user experience in collaborative project. Contributed to an in-house project leveraging Google Cloud Platform's VertexAI and multiple LLMs. Delivered a technical talk on Next.js to share knowledge across the team.",
    },
    {
      company: "Teknikum Oy",
      role: "Production Worker",
      period: "January 2017 – July 2017",
      description: "Manufacturing of various rubber parts with machinery. Process work in a factory. Three-shift-work. Helped clients by manufacturing batches of orders for them in time.",
    },
  ],
  education: [
    {
      institution: "Tampere University of Technology",
      degree: "Master of Science in Computer Science",
      period: "Ongoing",
      description: "Major: Software Development. Completed all required coursework; Currently working on Master's thesis.",
    },
    {
      institution: "Tampere University of Technology",
      degree: "Bachelor of Science in Computer Science",
      period: "2018 - 2023",
      description: "Major: Software Engineering; Minor: Industrial Engineering and Management.",
    },
  ],
};

