export const DATA = {
  name: "Riku Rainio",
  role: "Software Developer",
  about: "Building stuff with code",
  links: {
    email: "mailto:rainioriku@gmail.com",
    GitHub: "https://github.com/rikurainio",
    linkedIn: "https://linkedin.com/in/rikurainio",
    resume: "/cv.pdf", // Place in public folder
  },
  skills: [
    "TypeScript",
    "JavaScript",
    "C++",
    "Python",
    "Next.js",
    "React",
    "HTML",
    "CSS",
    "TailwindCSS",
    "Electron",
    "Node.js",
    "AWS",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Git",
    "Photoshop",
    "Sony Vegas Pro",
    "Figma",
    "Godot",
  ],
  projects: [
    {
      title: "Mennää",
      slug: "mennaa",
      description: "A Godot game project.",
      tech: ["Godot", "GDScript"],
      link: "https://github.com",
      image: "mennaa.png",
    },
    {
      title: "Drafter.lol",
      slug: "drafter-lol",
      description: "Designed, developed, and self-hosted a full-stack SaaS solution as part of a two-person team. Provided a strong alternative to existing market solutions, helping thousands of users.",
      tech: ["Next.js", "TypeScript", "PostgreSQL"],
      link: "https://drafter.lol",
      image: "drafter.png",
    },
    {
      title: "Sasken CV Database",
      slug: "sasken-cv-database",
      description: "A CV database application for Sasken.",
      tech: ["Next.js", "TypeScript", "PostgreSQL"],
      link: "https://github.com",
      image: "sasken.png",
    },
    {
      title: "Ideastorm",
      slug: "ideastorm",
      description: "A project for brainstorming and organizing ideas.",
      tech: ["Next.js", "TypeScript", "Tailwind CSS"],
      link: "https://github.com",
      image: "ideastorm.png",
      },
    {
      title: "LinkedInsanity",
      slug: "linkedinsanity",
      description: "A web application project.",
      tech: ["React", "TypeScript", "Tailwind CSS"],
      link: "https://github.com",
      image: "linkedinsanity.png",
    },
    // {
    //   title: "WarehouseJiuJitsu App",
    //   slug: "warehouse-jiu-jitsu-app",
    //   description: "A mobile application for warehouse jiu-jitsu management.",
    //   tech: ["React Native", "TypeScript", "Node.js"],
    //   link: "https://github.com",
    //   image: "https://placehold.co/600x400/000000/FFFFFF/png?text=WarehouseJiuJitsu",
    // },
  ],
  jobs: [
    {
      company: "DataAnnotation",
      role: "AI Annotator",
      period: "March 2024 – Present",
      description: "Improved text-based language models by rating prompts based on correctness, cohesiveness, verbosity, and context, including testing models with complex, carefully crafted prompts. Analyzed and corrected code to optimize performance, fix bugs, and enhance overall code quality in various projects.",
    },
    {
      company: "Buutti",
      role: "Software Developer",
      period: "April 2024 – October 2024",
      description: "Developed a full-stack webshop, working closely with the client to design and implement custom features that met their needs. Integrated APIs, optimized backend processes, and improved the frontend for a better user experience.",
    },
    {
      company: "Knowit",
      role: "Software Developer",
      period: "August 2022 – March 2024",
      description: "Led frontend development using React, integrating seamlessly with AWS backend services to deliver a quality user experience in collaborative project. Contributed to an in-house project leveraging Google Cloud Platform's VertexAI and multiple LLMs. Delivered a technical talk on Next.js to share knowledge across the team.",
    },
  ],
  education: [
    {
      institution: "Tampere University of Technology",
      degree: "Master of Science in Computer Science",
      period: "2025 - Present",
    },
    {
      institution: "Tampere University of Technology",
      degree: "Bachelor of Science in Computer Science",
      period: "2018 - 2023",
    },
  ],
};

